#!/usr/bin/python3
"""
Python script that takes in a URL, sends a request to the URL
and displays the body of the response
"""


if __name__ == "__main__":
    from urllib import request
    import sys

    try:
        with urllib.request.urlopen(sys.argv[1]) as hbtn:
            data = hbtn.read()
            print(data)

    except urllib.error.HTTPError as e:
        print(f'HTTPError: {e.code} - {e.reason}')
